"""Renew the Dhan access token before the market opens.

Dhan tokens last 24 hours and `/v2/RenewToken` only works on one that is still
alive: "If you try to renew an expired token, it will return an error." So this
runs on a schedule before the open, not as a recovery step -- once a token has
lapsed the replacement has to be generated by hand on web.dhan.co.

`--daemon` is the form the deployment uses, and it schedules against the *clock*
rather than against an interval from process start. That distinction matters
more than it looks. There is one token for the whole account, renewing it kills
the previous one, and the order-placing host holds a copy; an interval timer
therefore fires at whatever time the container last happened to restart, which
is eventually 11:00 or 14:00 -- invalidating the trading host's token in the
middle of a session, possibly with a position open. Pinned to a pre-open time,
the blast radius is a window when nothing is trading.

The token itself is never printed. `--check` reports validity without renewing,
which is the safe thing to run when you only want to know where you stand.

    python manage.py renew_dhan_token --check
    python manage.py renew_dhan_token
    python manage.py renew_dhan_token --daemon
"""
import time
from datetime import datetime, timedelta

from django.core.management.base import BaseCommand
from django.utils import timezone

from options_tracker.services import (
    _token_expiry,
    dhan_token_file,
    dhan_token_validity,
    get_dhan_credentials,
    renew_dhan_token,
)

# Well before the 09:15 open, and late enough that a renewal failure still
# leaves time to paste a token in by hand.
RENEW_AT_HOUR = 8
RENEW_AT_MINUTE = 20

# A restart can land at any hour, and the pinned time may be nearly a day away.
# If the token would not survive that wait, renew now and accept the timing.
RENEW_EARLY_WITHIN_HOURS = 5


def next_run(now):
    target = now.replace(
        hour=RENEW_AT_HOUR, minute=RENEW_AT_MINUTE, second=0, microsecond=0,
    )
    return target if target > now else target + timedelta(days=1)


class Command(BaseCommand):
    help = "Renew the 24-hour Dhan access token and persist it to DHAN_TOKEN_FILE."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Report the current token's validity and exit without renewing it.",
        )
        parser.add_argument(
            "--daemon",
            action="store_true",
            help=f"Stay running and renew at {RENEW_AT_HOUR:02d}:{RENEW_AT_MINUTE:02d} local time each day.",
        )

    def handle(self, *args, **options):
        access_token, client_id = get_dhan_credentials()
        path = dhan_token_file()
        self.stdout.write(f"client id {client_id or '(none)'}, token {'present' if access_token else 'MISSING'}")
        self.stdout.write(f"token file: {path or '(none configured)'}")

        if options["check"]:
            validity = dhan_token_validity()
            if validity:
                self.stdout.write(self.style.SUCCESS(f"token is live, valid until {validity}"))
            else:
                self.stdout.write(self.style.ERROR("Dhan would not confirm this token. Treat it as dead."))
            return

        if options["daemon"]:
            self._daemon()
            return

        self._renew_once(fatal=True)

    def _daemon(self):
        while True:
            now = timezone.localtime()
            due = next_run(now)
            expiry = _token_expiry(get_dhan_credentials()[0] or "")
            if expiry and expiry - now < timedelta(hours=RENEW_EARLY_WITHIN_HOURS) and expiry > now:
                # The token dies before the pinned slot comes round. Renewing off
                # schedule is worse than a pre-open renewal and far better than
                # letting it lapse, because a lapsed one cannot be renewed at all.
                self.stdout.write(f"token expires {expiry:%Y-%m-%d %H:%M}, ahead of the {due:%H:%M} slot; renewing now")
                self._renew_once(fatal=False)
                continue

            wait = (due - now).total_seconds()
            self.stdout.write(f"next renewal {due:%Y-%m-%d %H:%M %Z} ({wait / 3600:.1f}h away)")
            time.sleep(max(wait, 60))
            self._renew_once(fatal=False)
            # Past the slot by a minute, so the recomputed target is tomorrow's.
            time.sleep(90)

    def _renew_once(self, fatal):
        result = renew_dhan_token()
        if not result.get("ok"):
            # Loud, because everything downstream needs a token and nothing else
            # in this system can produce one.
            message = self.style.ERROR(f"renewal FAILED: {result.get('error')}")
            if fatal:
                raise SystemExit(message)
            self.stdout.write(message)
            # Do not hammer Dhan, and do not spin if the token is already dead.
            time.sleep(1800)
            return False

        validity = result.get("validity") or "(Dhan did not report a validity)"
        self.stdout.write(self.style.SUCCESS(f"renewed; valid until {validity}"))
        return True
