"""Renew the Dhan access token before the market opens.

Dhan tokens last 24 hours and `/v2/RenewToken` only works on one that is still
alive: "If you try to renew an expired token, it will return an error." So this
runs on a schedule before the open, not as a recovery step -- once a token has
lapsed the replacement has to be generated by hand on web.dhan.co.

The token itself is never printed. `--check` reports validity without renewing,
which is the safe thing to run when you only want to know where you stand.

    python manage.py renew_dhan_token --check
    python manage.py renew_dhan_token
"""
from django.core.management.base import BaseCommand

from options_tracker.services import (
    dhan_token_file,
    dhan_token_validity,
    get_dhan_credentials,
    renew_dhan_token,
)


class Command(BaseCommand):
    help = "Renew the 24-hour Dhan access token and persist it to DHAN_TOKEN_FILE."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Report the current token's validity and exit without renewing it.",
        )

    def handle(self, *args, **options):
        access_token, client_id = get_dhan_credentials()
        path = dhan_token_file()
        self.stdout.write(f"client id {client_id or '(none)'}, token {'present' if access_token else 'MISSING'}")
        self.stdout.write(f"token file: {path or '(none configured)'}")

        if options["check"]:
            validity = dhan_token_validity()
            if validity:
                self.stdout.write(self.style.SUCCESS(f"token is live, valid until {validity}"))
            else:
                self.stdout.write(self.style.ERROR("Dhan would not confirm this token. Treat it as dead."))
            return

        result = renew_dhan_token()
        if not result.get("ok"):
            # Loud, because everything downstream needs a token and nothing else
            # in this system can produce one.
            raise SystemExit(self.style.ERROR(f"renewal FAILED: {result.get('error')}"))

        validity = result.get("validity") or "(Dhan did not report a validity)"
        self.stdout.write(self.style.SUCCESS(f"renewed; valid until {validity}"))
