# Generated by Django 5.2.15 on 2026-07-23 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.CharField(max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DhanOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=80)),
                ('correlation_id', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IndexOISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(max_length=10)),
                ('call_oi', models.BigIntegerField(default=0)),
                ('put_oi', models.BigIntegerField(default=0)),
                ('pcr', models.FloatField(default=0.0)),
                ('regime', models.CharField(blank=True, max_length=40)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TipSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='MANUAL', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('raw_text', models.TextField(blank=True)),
                ('option_symbol', models.CharField(max_length=80)),
                ('direction', models.CharField(choices=[('CE', 'CE'), ('PE', 'PE')], max_length=2)),
                ('trade_style', models.CharField(choices=[('INTRADAY', 'Intraday'), ('SWING', 'Swing')], default='INTRADAY', max_length=12)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, max_length=40)),
                ('reason_tags', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CANDIDATE', 'Candidate'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20)),
                ('tip_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tip_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChartinkTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=80)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('live_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trigger_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('MONITORING', 'Monitoring'), ('MOVED', 'Moved to Tracker'), ('DISCARDED', 'Discarded')], default='MONITORING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='options_tracker.tipsignal')),
            ],
            options={
                'ordering': ['-trigger_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhan_order_id', models.CharField(blank=True, max_length=80)),
                ('correlation_id', models.CharField(blank=True, max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('journal_reason', models.TextField()),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='options_tracker.tipsignal')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
    ]
