# Generated by Django 5.2.15 on 2026-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipsignal',
            name='security_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tipsignal',
            name='source_ref',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
