# Generated by Django 5.2.15 on 2026-07-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_tracker', '0002_tipsignal_security_id_tipsignal_source_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('raw_text', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('is_tip_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='options_tracker.tipsignal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
