# Generated by Django 5.2.15 on 2026-07-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_tracker', '0007_tipsignal_dhan_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexOptionCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(max_length=10)),
                ('expiry_flag', models.CharField(default='WEEK', max_length=10)),
                ('expiry_code', models.PositiveSmallIntegerField(default=1)),
                ('relative_strike', models.CharField(max_length=10)),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('interval_minutes', models.PositiveSmallIntegerField(default=1)),
                ('timestamp', models.DateTimeField()),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('spot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('oi', models.BigIntegerField(default=0)),
                ('implied_volatility', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp', 'underlying', 'relative_strike', 'option_type'],
            },
        ),
        migrations.CreateModel(
            name='IndexOptionStrikeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', models.DecimalField(decimal_places=2, max_digits=14)),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('security_id', models.CharField(blank=True, max_length=40)),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price_change', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('oi', models.BigIntegerField(default=0)),
                ('previous_oi', models.BigIntegerField(default=0)),
                ('oi_change', models.BigIntegerField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('previous_volume', models.BigIntegerField(default=0)),
                ('implied_volatility', models.FloatField(default=0.0)),
                ('delta', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=0.0)),
                ('gamma', models.FloatField(default=0.0)),
                ('vega', models.FloatField(default=0.0)),
                ('top_bid_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('top_bid_quantity', models.BigIntegerField(default=0)),
                ('top_ask_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('top_ask_quantity', models.BigIntegerField(default=0)),
                ('buy_quantity', models.BigIntegerField(default=0)),
                ('sell_quantity', models.BigIntegerField(default=0)),
                ('depth', models.JSONField(blank=True, default=dict)),
                ('buildup', models.CharField(blank=True, max_length=30)),
                ('is_atm', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['strike', 'option_type'],
            },
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='atm_strike',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='call_oi_change',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='call_volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='max_pain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='pcr_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='put_oi_change',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='put_volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='resistance_strike',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='source',
            field=models.CharField(default='DHAN', max_length=20),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='support_strike',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='underlying_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='indexoisnapshot',
            name='underlying_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='indexoisnapshot',
            index=models.Index(fields=['underlying', '-created_at'], name='idx_oi_under_time'),
        ),
        migrations.AddIndex(
            model_name='indexoptioncandle',
            index=models.Index(fields=['underlying', '-timestamp'], name='idx_candle_under_time'),
        ),
        migrations.AddConstraint(
            model_name='indexoptioncandle',
            constraint=models.UniqueConstraint(fields=('underlying', 'expiry_flag', 'expiry_code', 'relative_strike', 'option_type', 'interval_minutes', 'timestamp'), name='unique_index_option_candle'),
        ),
        migrations.AddField(
            model_name='indexoptionstrikesnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='options_tracker.indexoisnapshot'),
        ),
        migrations.AddIndex(
            model_name='indexoptionstrikesnapshot',
            index=models.Index(fields=['security_id', '-snapshot'], name='idx_strike_security_snap'),
        ),
        migrations.AddIndex(
            model_name='indexoptionstrikesnapshot',
            index=models.Index(fields=['option_type', 'strike'], name='idx_strike_type_price'),
        ),
        migrations.AddConstraint(
            model_name='indexoptionstrikesnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot', 'strike', 'option_type'), name='unique_index_strike_snapshot'),
        ),
    ]
