# Generated by Django 5.2.15 on 2026-08-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options_tracker', '0009_fix_k_suffix_option_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPeriodSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=20)),
                ('account', models.CharField(blank=True, max_length=30)),
                ('period_label', models.CharField(max_length=40)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=120)),
                ('gross_realised', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('unrealised', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('charge_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['broker', 'period_from'],
                'constraints': [models.UniqueConstraint(fields=('broker', 'account', 'period_label'), name='unique_broker_period')],
            },
        ),
        migrations.CreateModel(
            name='BrokerPnlEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=20)),
                ('account', models.CharField(blank=True, max_length=30)),
                ('period_label', models.CharField(blank=True, max_length=40)),
                ('source_file', models.CharField(blank=True, max_length=120)),
                ('raw_symbol', models.CharField(max_length=90)),
                ('underlying', models.CharField(blank=True, max_length=40)),
                ('instrument_kind', models.CharField(blank=True, max_length=10)),
                ('option_type', models.CharField(blank=True, max_length=4)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('buy_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sell_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realised_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('unrealised_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'ordering': ['broker', 'raw_symbol'],
                'indexes': [models.Index(fields=['broker', 'period_label'], name='idx_pnl_broker_period'), models.Index(fields=['underlying'], name='idx_pnl_underlying')],
            },
        ),
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=60)),
                ('window_from', models.DateField()),
                ('window_to', models.DateField()),
                ('rows', models.IntegerField(default=0)),
                ('status', models.CharField(default='DONE', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'symbol'], name='idx_job_kind_sym')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'symbol', 'detail', 'window_from', 'window_to'), name='unique_download_job')],
            },
        ),
        migrations.CreateModel(
            name='StockEquityCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['symbol', 'timestamp'],
                'indexes': [models.Index(fields=['symbol', 'interval_minutes', 'timestamp'], name='idx_eq_sym_int_time')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'interval_minutes', 'timestamp'), name='unique_stock_equity_candle')],
            },
        ),
        migrations.CreateModel(
            name='StockOptionCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('expiry_code', models.PositiveSmallIntegerField(default=1)),
                ('relative_strike', models.CharField(max_length=10)),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('timestamp', models.DateTimeField()),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('spot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('oi', models.BigIntegerField(default=0)),
                ('implied_volatility', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['symbol', 'timestamp', 'relative_strike'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='idx_opt_sym_time'), models.Index(fields=['symbol', 'option_type', 'relative_strike'], name='idx_opt_sym_type_rel')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'expiry_code', 'relative_strike', 'option_type', 'interval_minutes', 'timestamp'), name='unique_stock_option_candle')],
            },
        ),
        migrations.CreateModel(
            name='TrackedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40, unique=True)),
                ('security_id', models.CharField(blank=True, max_length=20)),
                ('lot_size', models.PositiveIntegerField(default=0)),
                ('strike_step', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=60)),
                ('market_cap_band', models.CharField(blank=True, max_length=20)),
                ('contracts_traded', models.PositiveIntegerField(default=0)),
                ('realised_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('turnover', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('brokers', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-contracts_traded', 'symbol'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='idx_stock_active_prio')],
            },
        ),
    ]
